'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8806
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MSAscribe.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property adddenomat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adddenomat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addenvelopemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addenvelopemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addusermat24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addusermat24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backarrow24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backarrow24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backarrow32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backarrow32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barn_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barn_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bounced24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bounced24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property broom_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("broom_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property businessgroup_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("businessgroup_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property businessgroup_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("businessgroup_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancelmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chapelLogo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("chapelLogo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property checkmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chequemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chequemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coinsfilled24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coinsfilled24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property creditcardmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creditcardmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property crowdfunding_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crowdfunding_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property currency_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("currency_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property darrowmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darrowmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property decline24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("decline24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deletemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deletemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dellinkmat24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dellinkmat24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dellinkmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dellinkmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property door_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("door_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dowloadmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dowloadmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eldersmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eldersmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filtermat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filtermat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folderfilledb_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folderfilledb_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fusermat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fusermat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property garage_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("garage_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property garagemat24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("garagemat24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property getcash_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("getcash_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gg_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gg_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property graph_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graph_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gridmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gridmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property groupmessage_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("groupmessage_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property groupobjects_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("groupobjects_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconChapel() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconChapel", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property listmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lockKey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockKey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mappinpoint_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mappinpoint_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meeting_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meeting_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minusmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minusmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mobilemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mobilemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property offsheetmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("offsheetmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property onlinesupport_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onlinesupport_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolderf_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolderf_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openenvelope_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openenvelope_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property personmat24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personmat24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property piston_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("piston_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property postmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refreshmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rent_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rent_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportbank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportbank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportbasket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportbasket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportdough() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportdough", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportfile_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportfile_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportpeople() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportpeople", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportring() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportring", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportstack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportstack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportwarehse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reportwarehse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rubblecoin24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rubblecoin24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ruble24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ruble24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savemat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savemat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savenextmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savenextmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property searchmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searchmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sheetmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sheetmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property staffmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("staffmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stripe_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stripe_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stripeb_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stripeb_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suppmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suppmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tickgreen48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tickgreen48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbox_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbox_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transfermat24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transfermat24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tscollections() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tscollections", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tsexpenses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsexpenses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tsoffertory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsoffertory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tsusersm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsusersm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upload_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usergrpmat24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usergrpmat24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usergrpmat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usergrpmat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermat30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermat30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ushermat48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ushermat48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
